### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by wangcong607** [AutoAILab/FusionDepth#1]
Hello, thanks for your work. But when I run 'bash prepare_4beam_data_for_prediction.sh', there are no documents here such as sparsify.py, splits. Please make sure your code is complete. Thanks for your reply.

**Comment by fengziyue** [comment]
Hi:

Thank you for your interest, I have uploaded the missing 'splits' and sparsify.py, please let me know if there is anything else missed

**Comment by wangcong607** [comment]
Thanks for your reply.
