### ISSUE TITLE
Absolute depth or relative depth? 

### ISSUE THREAD

**Issue by Ecalpal** [AutoAILab/FusionDepth#10]
Hello! Thank you for your splendid work! But I have some questions about what we get is absolute depth or relative depth by using your model?

**Comment by fengziyue** [comment]
Hi:
Thank you for your interest, the output by default is relative depth, but since we have access to sparse LiDAR data, a simple median scaling can restore the absolute metric depth.

**Comment by Ecalpal** [comment]
Thanks for your quickly reply!
