### ISSUE TITLE
Error when run evaluation by pretrained model

### ISSUE THREAD

**Issue by mysephi** [AutoAILab/FusionDepth#11]
Thank you for your interesting work. 
I want to confirm the performance of depth completion task. I prepared the pretrained model ResNet50 and validation data(data_depth_selection).
When I run
`python evaluate_completion.py --load_weights_folder log/res50/models/weights_best --eval_mono --nbeams 4 --num_layers 50`
It returns the following error.
```
Traceback (most recent call last):
  File "evaluate_completion.py", line 373, in <module>
    evaluate(options.parse())
  File "evaluate_completion.py", line 174, in evaluate
    output = depth_decoder(features, beam_features=beam_features)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/localDisk/yangjunjie/scripts/3d/FusionDepth/networks/depth_decoder.py", line 70, in forward
    x = input_features[-1] + beam_features[-1]
RuntimeError: The size of tensor a (20) must match the size of tensor b (38) at non-singleton dimension 3
```
It seems that input image is resized while the corresponding depth map keeps the same.

**Comment by fengziyue** [comment]
Hi:

Thanks for your interest in our work!
Which script did you use to generate the PDR? Could you check the size of the input image and the PDR?

**Comment by mysephi** [comment]
I have read through the corresponding scripts in prepare_4beam_data_for_prediction.sh.
**sparsify.py, export_gt_depth.py and gen2channel.py** does nothing to val dataset in completion task , so I ran evaluate_completion.py directly.

**Comment by fengziyue** [comment]
The prepare_4beam_data_for_prediction.sh is only for the depth prediction task, you may need to do similar preprocessing to the completion task before evaluation.
