### ISSUE TITLE
Running trainer.py failed运行trainer.py失败

### ISSUE THREAD

**Issue by henrycddj** [AutoAILab/FusionDepth#12]
File "trainer.py", line 272, in process_batch
    inputs[key] = ipt.to(self.device)
AttributeError: 'list' object has no attribute 'to'

may i ask how to solve this problem?  I tried but failed.
请问怎么解决这个问题呢?我试了一些方法,但失败了

**Comment by fengziyue** [comment]
Could you add a print command to see which 'inputs' key caused the error?
你可以试一下加一个print来检查哪个元素导致的问题：
<img width="305" alt="Screen Shot 2022-06-14 at 11 38 54 AM" src="https://user-images.githubusercontent.com/21237230/173618820-ab62998f-0c86-4926-9131-5e2d576eb5fd.png">

**Comment by henrycddj** [comment]
Training
key : date
ipt : ['2011_09_30', '2011_09_30']
Traceback (most recent call last):
  File "trainer.py", line 762, in <module>
    trainer.train()
  File "trainer.py", line 226, in train
    self.run_epoch()
  File "trainer.py", line 241, in run_epoch
    outputs, losses = self.process_batch(inputs)
  File "trainer.py", line 276, in process_batch
    inputs[key] = ipt.to(self.device)
AttributeError: 'list' object has no attribute 'to'
我尝试输出key和ipt的值, 但是ipt是一个list,我的数据目录参考了你在其他问题中的回答,代码没有其他改动

**Comment by fengziyue** [comment]
Can you try to modify the code as follows?
你可以试一下这么修改吗？
<img width="339" alt="Screen Shot 2022-06-15 at 11 32 04 AM" src="https://user-images.githubusercontent.com/21237230/173867229-0a333c4d-b7a5-477c-9b8b-2d9457b8ceee.png">

**Comment by henrycddj** [comment]
Thank you for your patience, now the problem is solved
感谢你耐心的解答, 现在问题解决了

**Comment by lmomoy** [comment]
你好，当我运行inf_depth_map.py时出现了相似的问题
![image](https://user-images.githubusercontent.com/49771303/179967669-1b786213-5197-485a-8346-9b267466cbb7.png)
而当我按照这种解决方式改后，问题仍然存在

> Can you try to modify the code as follows? 你可以试一下这么修改吗？ <img alt="Screen Shot 2022-06-15 at 11 32 04 AM" width="339" src="https://user-images.githubusercontent.com/21237230/173867229-0a333c4d-b7a5-477c-9b8b-2d9457b8ceee.png">

**Comment by lmomoy** [comment]
> 你好，当我运行inf_depth_map.py时出现了相似的问题 ![image](https://user-images.githubusercontent.com/49771303/179967669-1b786213-5197-485a-8346-9b267466cbb7.png) 而当我按照这种解决方式改后，问题仍然存在
> 
> > Can you try to modify the code as follows? 你可以试一下这么修改吗？ <img alt="Screen Shot 2022-06-15 at 11 32 04 AM" width="339" src="https://user-images.githubusercontent.com/21237230/173867229-0a333c4d-b7a5-477c-9b8b-2d9457b8ceee.png">

似乎我应该改成这样才能运行，这样是正确的吗？
![image](https://user-images.githubusercontent.com/49771303/179971442-54fdf0a2-32ec-420e-9e37-5f350889c750.png)

**Comment by fengziyue** [comment]
对的，path和date都是string，好像都不能放到显存里面
