### ISSUE TITLE
运行refiner.py时loss为nan

### ISSUE THREAD

**Issue by lmomoy** [AutoAILab/FusionDepth#14]
作者你好，很感谢你的工作，当我运行到refiner.py时我发现loss为nan，经过debug我发现主要是因为gdc_loss为nan，这是我各个变量的值，希望你能帮助我找出问题
![image](https://user-images.githubusercontent.com/49771303/180119021-1918b09e-ab11-434f-8a3f-b2ebac3cc799.png)
![image](https://user-images.githubusercontent.com/49771303/180119055-5d2a4080-00ee-45ee-b5d7-659b951f075d.png)
![image](https://user-images.githubusercontent.com/49771303/180119092-8be70652-e5fe-44e0-ac50-ddb7918a825e.png)

**Comment by lmomoy** [comment]
> 你好，谢谢你对这个工作的兴趣！
> 
> 你可以检查一下 "depth" 和 "gdc_out" 完整的值吗？有没有哪些位置异常的？

depth似乎全是100，这应该是不正常的？

**Comment by lmomoy** [comment]
想请教一下作者训练的时候batchsize和学习率设置的是多少，我似乎是因为将batchsize调成了32所以出现了这样的问题

**Comment by lmomoy** [comment]
似乎是因为我将batchsize调成了32，作者训练时是按照batchsize=8，lr=1e − 4吗？

**Comment by fengziyue** [comment]
我训练的时候batchsize一般是8或12， lr=1e-4。你把batchsize调小以后能解决问题吗？
刚初始化的时候depth全是100应该是可能的，训练一段时间以后还一直是100就有问题了

**Comment by lmomoy** [comment]
> 我训练的时候batchsize一般是8或12， lr=1e-4。你把batchsize调小以后能解决问题吗？ 刚初始化的时候depth全是100应该是可能的，训练一段时间以后还一直是100就有问题了

是的，似乎是batchsize的问题，另外想请教一下，为什么posenet的输入，image为T‘时刻的，而lidar仍然为T时刻的呢

**Comment by fengziyue** [comment]
请问你找出batchsize过大导致nan的原因了吗？

谢谢指出这个问题，这是画图时候的错误，其实posenet输入的image和LiDAR都是T+T'时刻的

**Comment by lmomoy** [comment]
> 请问你找出batchsize过大导致nan的原因了吗？
> 
> 谢谢指出这个问题，这是画图时候的错误，其实posenet输入的image和LiDAR都是T+T'时刻的

我猜测可能是bs和lr不匹配的问题，我增大了bs但是没有相应增大lr

**Comment by lmomoy** [comment]
还想请教一下，文中这两个说法是不是同一种网络配置
