### ISSUE TITLE
Error in Preprocessing Data

### ISSUE THREAD

**Issue by Renatusphere** [AutoAILab/FusionDepth#15]
Thanks for your work!
I'm running the "bash prepare_4beam_data_for_prediction.sh". However, the data "/Kitti_RAW_Data/2011_09_26/2011_09_26_drive_0002_sync/4beam/0000000069.bin" seems to be needed.
![})7CU%D5M$9`KBYEK5PLFT9](https://user-images.githubusercontent.com/93418632/180225339-72c79aad-6de3-48b7-8b7f-96192e42efae.png)

I wonder if it's the same as the one in the standard kitti dataset, which is "/data/Kitti_RAW_Data/2011_09_26/2011_09_26_drive_0002_sync/velodyne_points/data/0000000069.bin"
If not, how can I get the series of dataset mentioned in the image? Thanks!

**Comment by Renatusphere** [comment]
And is the preprocess necessary for the work of training? When I run the "python trainer.py", it seems another document is needed:
'/data/Kitti_RAW_Data/2011_09_30/2011_09_30_drive_0028_sync/2channel/5001_r_False.npy'
![%~80(Z$FK}35)@ 9@GJPIKN](https://user-images.githubusercontent.com/93418632/180226760-6ee5c995-8dc6-40d8-a46d-3ca9ad6b405c.png)

 I'm puzzeled about how to get these data.

**Comment by Renatusphere** [comment]
Thank you for your response!

It seems that the error happens in the process of loading the velodyne data. In the code below, it tries to load raw data from velo_filename: "/data/Kitti_RAW_Data/2011_09_26/2011_09_26_drive_0002_sync/4beam/0000000069.bin" 

![image](https://user-images.githubusercontent.com/93418632/180412400-5d62899b-f414-4b16-a7e3-c2db98a42827.png)

However, I assume that this file should have been the output file, so the velo_filename is incorrect.

I tried to modify my output path, but it didn't work. It turned out to be the same error.

Should I modify the code of splicing velo_filename? Thank you again!

**Comment by fengziyue** [comment]
The raw 64-beam Velodyne data is 'velodyne_points/data/xxx.bin' while the sparsified data is '4beam/xxx.bin'. The variable name "velo_filename" here is not clear enough, you are welcome to modify it and submit a pull request. 

Could you check where your sparsify.py outputted the '4beam/xxx.bin' files? that's what the code in your screenshot supposed to load.

**Comment by Renatusphere** [comment]
It turned out that I missed a "/" in the end of  ptc_path, which lead to no output. 

Thanks a lot for your great work and enthusiastic response!
