### ISSUE TITLE
请问为什么论文里Initial Depth结果与预训练模型结果不一样？

### ISSUE THREAD

**Issue by lmomoy** [AutoAILab/FusionDepth#16]
请问为什么论文里Initial Depth结果与预训练模型结果不一样？

![image](https://user-images.githubusercontent.com/49771303/180940759-8e31aaf2-c646-4793-a122-e0eff2fd08df.png)

论文中为0.078

**Comment by fengziyue** [comment]
我们在写论文的时候，选取了4条比较集中的lidar线。后来发现选取分散一些的线能取得更好的结果。所以预训练模型和这里的代码都是基于新的实验。

**Comment by lmomoy** [comment]
> 我们在写论文的时候，选取了4条比较集中的lidar线。后来发现选取分散一些的线能取得更好的结果。所以预训练模型和这里的代码都是基于新的实验。

明白了，谢谢你的解答
