### ISSUE TITLE
同样的权重文件训练过程中val的结果与evaluate_depth.py运行的结果不一致？

### ISSUE THREAD

**Issue by lmomoy** [AutoAILab/FusionDepth#18]

**Comment by fengziyue** [comment]
请问大概相差多少？

**Comment by lmomoy** [comment]
我没有跑源代码，进行了一些修改，这是训练过程中val的结果
![image](https://user-images.githubusercontent.com/49771303/183789253-254d1121-aebd-4676-b01e-19f576b53e28.png)

这是evaluate_depth.py运行的结果
![image](https://user-images.githubusercontent.com/49771303/183789314-ead553b8-d021-44cd-b8d6-bb1790ba0411.png)

**Comment by fengziyue** [comment]
`evaluate_depth.py` 的结果是四舍五入到小数点后3位的。另外它和训练时的val函数的实现有一点细微的差别，这个量级的误差可以忽略的。
