### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by brandleyzhou** [AutoAILab/FusionDepth#2]
Hi Ziyue,

Thanks for releasing this fantastic work. I have a quick question about your video demo. Can you give some suggestions about point cloud visualization? like any tools or software etc. 

Thanks,
Hang

**Comment by fengziyue** [comment]
Hi brandley:

Thank you for your interest, I use open3d for point cloud visualization, it has python interface that you can update the point cloud automaticly
