### ISSUE TITLE
About the depth completion task

### ISSUE THREAD

**Issue by dzin18** [AutoAILab/FusionDepth#4]
The RMSE performance of the depth completion improved a lot compared to other self-supervised methods, but the depth-completion training script completor.py is not provided.

**Comment by fengziyue** [comment]
Hi @dzin18 : 
 
Thank you for your interest, I just uploaded the completor.py

**Comment by dzin18** [comment]
> Hi @dzin18 :
> 
> Thank you for your interest, I just uploaded the completor.py

thanks
