### ISSUE TITLE
The evaluation_depth.py is missing

### ISSUE THREAD

**Issue by WeixuWang** [AutoAILab/FusionDepth#5]
Hello, I want to follow your work, but I can't find any files named evaluation_depth.py, could you help me
?

**Comment by fengziyue** [comment]
Hi @WeixuWang : 
Thank you for your interest, I just uploaded the 'evaluate_depth.py', please let me know if there is anything else missed

**Comment by WeixuWang** [comment]
Thank you for your reply. I found that the code still lacks files like 'export_detection.py" and 'evaluate_completion.py". In addition, I see that you have used the kitti raw dataset, kitti depth dataset and kitti detection dataset to train your model, could you show the directory structure of the whole dataset ?

**Comment by fengziyue** [comment]
Hi @WeixuWang 

I just uploaded those files, following is a screenshot of my dataset structure, 

![image](https://user-images.githubusercontent.com/21237230/149871668-88831fe2-d75f-40a8-ae05-6f84abd8fe11.png)

![image](https://user-images.githubusercontent.com/21237230/149871902-9770f004-4b28-4246-a416-1761d7e11ea5.png)
In each '*_sync' directory, I think you only need to prepare the 'image_02' and 'velodyne_points' folder.
