### ISSUE TITLE
about static scenario

### ISSUE THREAD

**Issue by dzin18** [AutoAILab/FusionDepth#6]
Hello, I have a question about the PoseNet. Can PoseNet handle the situation where the car stops at the road intersection? In this scenario, the front and rear frames are relatively static, what is the output of PoseNet?

**Comment by fengziyue** [comment]
Hi @dzin18 

Thank you for your interest, I didn't dig into this scenario, but this code is developed from Monodepth2, which has an 'auto_masking' mechanism to handle this scenario as shown below:

https://github.com/AutoAILab/FusionDepth/blob/76bb79ceb4d4c7e76d171957c46e75bc0597c621/trainer.py#L514

![image](https://user-images.githubusercontent.com/21237230/149870376-a7a9cf8b-64a7-4364-8fbf-4c9711f37321.png)

**Comment by fengziyue** [comment]
If you found anything interesting in this scenario, welcome to post and discuss here
